### ISSUE TITLE
Raise EOFError 

### ISSUE THREAD

**Issue by liujiqiangresearch** [facebookresearch/UnsupervisedMT#16]
When the NMT runs for a while, the following error is reported. My run command is as follows.
Is there any parameter that is too large? How to improve the stability of the program?
``` 
python main.py  -exp_name base3  --transformer True  --n_enc_layer 3  --n_dec_layer 3  --share_enc 2     --share_dec 2 --share_lang_emb True  --share_output_emb True --langs 'en,fr' --n_mono -1 --mono_dataset 'en:./data/mono/all.en.tok.60000.pth,,;fr:./data/mono/all.fr.tok.60000.pth,,' 
--para_dataset 'en-fr:,./data/para/dev/newstest2013-ref.XX.60000.pth,./data/para/dev/newstest2014-fren-src.XX.60000.pth' 
--mono_directions 'en,fr'  --word_dropout 0.1 --word_blank 0.2 --pivo_directions 'fr-en-fr,en-fr-en' 
--pretrained_emb './data/mono/all.en-fr.60000.vec' --pretrained_out True 
--lambda_xe_mono '0:1,100000:0.1,300000:0' --lambda_xe_otfd 1 --otf_num_processes 15 
--otf_sync_params_every 1000  --enc_optimizer adam,lr=0.0001  --epoch_size 500000 
--stopping_criterion bleu_en_fr_valid,10
```

Traceback (most recent call last):
  File "main.py", line 317, in <module>
    batches = next(otf_iterator)
  File "/mnt/disk-c/liujiqiang/low-resourceMT/UnsupervisedMT/en2fr/baseline/NMT/src/trainer.py", line 561, in otf_bt_gen_async
    results = cache[0].gen()
  File "/mnt/disk-c/liujiqiang/low-resourceMT/UnsupervisedMT/en2fr/baseline/NMT/src/multiprocessing_event_loop.py", line 203, in gen
    return next(self.generator)
  File "/mnt/disk-c/liujiqiang/low-resourceMT/UnsupervisedMT/en2fr/baseline/NMT/src/multiprocessing_event_loop.py", line 73, in fetch_all_result_generator
    result_type, result = self.return_pipes[rank].recv()
  File "/home/liujq/Python-3.6.4/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/liujq/Python-3.6.4/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/liujq/Python-3.6.4/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

**Comment by jplu** [comment]
Up! I get the same issue with the same logs.

**Comment by jplu** [comment]
I did update my Pytorch version to ```1.0.0.dev20181022``` and still the same exception :(

**Comment by jplu** [comment]
I did solved the issue by using Python 3.5.3, apparently Python 3.6 does not likes concurencies when multiple heavy processes already run on the machine :(

**Comment by glample** [comment]
Did you have to change something in the code? Or just using another version of Python solved the issue?

**Comment by jplu** [comment]
Well, to be more specific, firstly I noticed that adding a timeout to the ```poll()``` function at line 72 partially solved the problem, because apparently there was a sync issue between the read/write in the Pipe. Unfortunatelly, this solution was slowing the process a lot and sometimes, depending of the usage of the machine, was changing. Then I wanted to see if the Python 3.5 version was working or not, I did install it, run the training and it worked perfectly without changing any line of code.

**Comment by frankang** [comment]
In my case, this might be caused by a mismatch between the pytorch version (compiled on cuda9.0) and the cudatoolkit version (10.0). I reinstalled the correct pytorch, cudatoolkit, and upgraded to python 3.7.7, issue gone.

**Comment by vincentg** [comment]
FYI, this issue was solved in Python 3.7 by this python issue (see the same stack trace there): 
https://bugs.python.org/issue31069

It can likely be closed
