### ISSUE TITLE
"RuntimeError: received 0 items of ancdata" in  otf_bt_gen_async 

### ISSUE THREAD

**Issue by tobyyouup** [facebookresearch/UnsupervisedMT#17]
H when I run the unsupervised NMT codes, it raises the error after running for a while:

`Traceback (most recent call last):
  File "../main.py", line 317, in <module>
    batches = next(otf_iterator)
  File "/data/xutan/nmt/unsupervised/UnsupervisedMT/NMT/src/trainer.py", line 561, in otf_bt_gen_async
    results = cache[0].gen()
  File "/data/xutan/nmt/unsupervised/UnsupervisedMT/NMT/src/multiprocessing_event_loop.py", line 203, in gen
    return next(self.generator)
  File "/data/xutan/nmt/unsupervised/UnsupervisedMT/NMT/src/multiprocessing_event_loop.py", line 73, in fetch_all_result_generator
    result_type, result = self.return_pipes[rank].recv()
  File "/home/xutan/anaconda3/lib/python3.6/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "/home/xutan/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 201, in rebuild_storage_fd
    fd = df.detach()
  File "/home/xutan/anaconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/home/xutan/anaconda3/lib/python3.6/multiprocessing/reduction.py", line 182, in recv_handle
    return recvfds(s, 1)[0]
  File "/home/xutan/anaconda3/lib/python3.6/multiprocessing/reduction.py", line 161, in recvfds
    len(ancdata))
RuntimeError: received 0 items of ancdata`

during the back translation process.

So what's the problem?  Does it mean the workload of back translation is too heavy?

I put the full log here:
https://gist.github.com/tobyyouup/8426bb216d05482efd0bbdc8dcbd04e5

Look forward to your reply. Thanks!

**Comment by tobyyouup** [comment]
@glample   Can you help to check this problem? Thanks very much!

**Comment by tobyyouup** [comment]
Yes,  this only happened when sampling 3 languages. For 2 languages, this never happens.

I will try the hparams you mentioned.
