### ISSUE TITLE
Error when dimension of fastText embedding is changed

### ISSUE THREAD

**Issue by shawnzaru** [facebookresearch/UnsupervisedMT#19]
I changed the dimension of the fastText utility from 512 to 128 to adapt to my own corpora:

```
$FASTTEXT skipgram -epoch $N_EPOCHS -minCount 0 -dim **128** 
     -thread $N_THREADS -ws 5 -neg 10 -input $CONCAT_BPE -output $CONCAT_BPE
```

The result is as follows:

```
INFO - 09/16/18 15:31:04 - 0:00:05 - Reloading embeddings from ./mydata/mono/all.yy-xx.500.vec ...
Traceback (most recent call last):
  File "main.py", line 242, in <module>
    encoder, decoder, discriminator, lm = build_mt_model(params, data)
  File "/local/home/qwang/UnsupervisedMT/NMT/src/model/__init__.py", line 98, in build_mt_model
    return build_attention_model(params, data, cuda=cuda)
  File "/local/home/qwang/UnsupervisedMT/NMT/src/model/attention.py", line 813, in build_attention_model
    initialize_embeddings(encoder, decoder, params, data)
  File "/local/home/qwang/UnsupervisedMT/NMT/src/model/pretrain_embeddings.py", line 90, in initialize_embeddings
    pretrained_0, word2id_0 = reload_embeddings(params.pretrained_emb, params.emb_dim)
  File "/local/home/qwang/UnsupervisedMT/NMT/src/model/pretrain_embeddings.py", line 76, in reload_embeddings
    return reload_txt_emb(path, dim)
  File "/local/home/qwang/UnsupervisedMT/NMT/src/model/pretrain_embeddings.py", line 48, in reload_txt_emb
    assert dim == int(split[1])
AssertionError
```

**Comment by glample** [comment]
Hi,

Did you also specify the new dimension in the running command? There is a parameter `--emb_dim` whose default value is `512`.

Try to add: `--emb_dim 128`

However, I would recommend using `512` as using embeddings of dimension `512` works usually significantly better than `128`.

**Comment by shawnzaru** [comment]
Thanks.
