### ISSUE TITLE
CUDA out of memory during test set evaluation only

### ISSUE THREAD

**Issue by dkavaler** [facebookresearch/UnsupervisedMT#58]
I have a parallel validation set and test set of size 1000 observations each (training set size 37755), binarized using preprocess.py. Monolingual data set is the same as the parallel dataset (with changed file names). I am getting the following traceback during test set evaluation at the end of the first epoch:

```
Traceback (most recent call last):
  File "main.py", line 356, in <module>
    main(params)
  File "main.py", line 339, in main
    scores = evaluator.run_all_evals(trainer.epoch)
  File "XXX/UnsupervisedMT/NMT/src/evaluator.py", line 260, in run_all_evals
    self.eval_para(lang1, lang2, data_type, scores)
  File "XXX/UnsupervisedMT/NMT/src/evaluator.py", line 154, in eval_para
    decoded = self.decoder(encoded, sent2[:-1], lang2_id)
  File "XXX/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "XXX/UnsupervisedMT/NMT/src/model/transformer.py", line 227, in forward
    incremental_state=incremental_state,
  File "XXX/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/XXX/UnsupervisedMT/NMT/src/model/transformer.py", line 445, in forward
    incremental_state=incremental_state, need_weights=False,
  File "XXX/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/XXX/UnsupervisedMT/NMT/src/modules/multihead_attention.py", line 140, in forward
    attn_weights = F.softmax(attn_weights, dim=-1)
  File "XXX/pytorch/lib/python3.6/site-packages/torch/nn/functional.py", line 1188, in softmax
    ret = input.softmax(dim)
```

I have the following model specification (very small model to test this issue):

```
python main.py --exp_name viz_test --dump_path $DATA_DIR --save_periodic 1 --seed 1337 --dropout 0.3 --max_len 100 \
--mono_dataset $MONO_DATASET --para_dataset $PARA_DATASET \
--transformer True --n_enc_layers 2 --n_dec_layers 2 --share_enc 2 --share_dec 2 --emb_dim 512 --hidden_dim 512 \
--share_encdec_emb True --share_decpro_emb True --share_output_emb True --share_lang_emb True \
--encoder_attention_heads 4 --decoder_attention_heads 4 --transformer_ffn_emb_dim 512 \
--n_mono -1 --n_para -1 \
--langs 'src,tgt' --mono_directions 'src,tgt' --para_directions 'src-tgt,tgt-src' --pivo_directions 'src-tgt-src,tgt-src-tgt' \
--word_shuffle 3 --word_dropout 0.1 --word_blank 0.2 \
--lambda_xe_mono '0:1,100000:0.1,300000:0' --lambda_xe_para 1 --lambda_xe_otfd 1 --otf_num_processes 32 \
--otf_sync_params_every 1000 --enc_optimizer adam,lr=0.0001 --epoch_size 5000 \
--stopping_criterion bleu_asm_code_valid,10 \
--batch_size 2 --max_vocab 1000
```

GPU: 16 GB Tesla P100
Driver: 384.130

Solutions I've tried:

1. Reducing model size / batch size / vocabulary size
2. Swapping validation and test sets (still OOM on test set evaluation stage)
3. Replication validation set to be both valid and test sets

I've also noticed that in the experiment directory the ref.src-tgt.test.txt file is 998 lines, and ref.src-tgt.valid.txt is 78 lines (according to wc). Is this expected, given the input files are 1000 lines each?

**Comment by gitlost-murali** [comment]
@dkavaler Look at batch_size in get_iterator() function in evaluator.py. It is set to 32. That might help you.
