### ISSUE TITLE
Error duing pre-processing stage: en_es

### ISSUE THREAD

**Issue by sedflix** [facebookresearch/UnsupervisedMT#67]
I modified the get_data_enfr.sh script [to get this script](https://github.com/sedflix/UnsupervisedMT/blob/master/NMT/get_data_enes.sh). I'm getting the following error during the preprocessing stage. 
Which stage might have gone wrong?

```
EN monolingual data concatenated in: /app/NMT/data/mono/all.en
ES monolingual data concatenated in: /app/NMT/data/mono/all.es
EN monolingual data tokenized in: /app/NMT/data/mono/all.en.tok
ES monolingual data tokenized in: /app/NMT/data/mono/all.es.tok
BPE learned in /app/NMT/data/mono/bpe_codes
BPE codes applied to EN in: /app/NMT/data/mono/all.en.tok.60000
BPE codes applied to ES in: /app/NMT/data/mono/all.es.tok.60000
EN vocab in: /app/NMT/data/mono/vocab.en.60000
ES vocab in: /app/NMT/data/mono/vocab.es.60000
Full vocab in: /app/NMT/data/mono/vocab.en-es.60000
Binarizing data...
/app/NMT/data/mono/vocab.en-es.60000
Traceback (most recent call last):
  File "/app/NMT/preprocess.py", line 28, in <module>
    dico = Dictionary.read_vocab(voc_path)
  File "/app/NMT/src/data/dictionary.py", line 111, in read_vocab
    assert len(line) == 2, (i, line)
AssertionError: (17224, ['1915'])
```

**Comment by zhang-jinyi** [comment]
I think there is a space in your dictionary.
Please use this [https://github.com/facebookresearch/XLM/blob/master/src/data/dictionary.py ](https://github.com/facebookresearch/XLM/blob/master/src/data/dictionary.py)to replace your dictionary.py
