### ISSUE TITLE
How to slove this problem load_mono_data     assert data['dico'][lang] == mono_data['dico'] AssertionError

### ISSUE THREAD

**Issue by JxuHenry** [facebookresearch/UnsupervisedMT#75]
INFO - 04/06/19 15:17:42 - 0:00:04 - ============ Monolingual data (en)
INFO - 04/06/19 15:17:42 - 0:00:04 - Loading data from ./data/mono/all.en.tok.60000.pth ...
INFO - 04/06/19 15:17:45 - 0:00:08 - 1036379321 words (60536 unique) in 10000000 sentences. 0 unknown words (0 unique).
en
data['dico']:
{'ch': <src.data.dictionary.Dictionary object at 0x7fba7c176b38>, 'en': <src.data.dictionary.Dictionary object at 0x7fba7bba6c50>}
mono_data['dico']:
<src.data.dictionary.Dictionary object at 0x7fba702dd978>
data['dico'][lang]:
<src.data.dictionary.Dictionary object at 0x7fba7bba6c50>
Traceback (most recent call last):
  File "main.py", line 358, in <module>
    main(params)
  File "main.py", line 242, in main
    data = load_data(params)
  File "/data/xj/UNMT/UnsupervisedMT-master/NMT/src/data/loader.py", line 509, in load_data
    load_mono_data(params, data)
  File "/data/xj/UNMT/UnsupervisedMT-master/NMT/src/data/loader.py", line 292, in load_mono_data
    assert data['dico'][lang] == mono_data['dico']
AssertionError

**Comment by glample** [comment]
This means that you used different dictionaries to pre-process your different datasets. Each .pth file must be generated using the preprocess.py script with the same dictionary.

**Comment by glample** [comment]
Btw I would recommend looking at https://github.com/facebookresearch/XLM, which contains a better implementation for unsupervised MT, and provides much better results than this code.

**Comment by JxuHenry** [comment]
> This means that you used different dictionaries to pre-process your different datasets. Each .pth file must be generated using the preprocess.py script with the same dictionary.

All the .pth file were used the preprpcess.py script with the same dictionary.

**Comment by JxuHenry** [comment]
> This means that you used different dictionaries to pre-process your different datasets. Each .pth file must be generated using the preprocess.py script with the same dictionary.

Could you be more specific about what is the same dictionary,I used the same corpus. And all the .pth file generated using the preprocess.py script

**Comment by JxuHenry** [comment]
> Btw I would recommend looking at https://github.com/facebookresearch/XLM, which contains a better implementation for unsupervised MT, and provides much better results than this code.

OK thanks a lot sir, I will looking at the code which you recommended

**Comment by glample** [comment]
The line `assert data['dico'][lang] == mono_data['dico']` is failing which means that these two dictionaries are different. Can you check how different they are? Like, is the vocabulary size different, print the words inside each dictionary or something?

**Comment by JxuHenry** [comment]
> 该行`assert data['dico'][lang] == mono_data['dico']`失败，这意味着这两个词典是不同的。你能看看它们有多么不同吗？比如，词汇量大小是不同的，打印每个字典里面的单词还是什么？

OK, I see,thank you very much
